CREATE TABLE IF NOT EXISTS `cdme_location` (
`id` BIGINT NOT NULL AUTO_INCREMENT,
`longitude` DOUBLE NOT NULL,
`latitude` DOUBLE NOT NULL,
PRIMARY KEY(`id`))
ENGINE = INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `cdme_noise_data`(
`id` BIGINT NOT NULL AUTO_INCREMENT, 
`location_id` BIGINT NOT NULL, 
`noise_level` VARCHAR(100) NOT NULL, 
`date_time` DATETIME,
PRIMARY KEY(`id`))
ENGINE = INNODB DEFAULT CHARSET=utf8;
