INSERT INTO `cdme_admin_1_region` (`name`) VALUES 
('Central Province'),
('Eastern Province'),
('North Central Province'),
('Northern Province'),
('North Western Province'),
('Sabaragamuwa Province'),
('Southern Province'),
('Uva Province'),
('Western Province');

INSERT INTO `cdme_admin_2_region` (`name`) VALUES
('Ampara'),
('Anuradhapura'),
('Badulla'),
('Batticaloa'),
('Colombo'),
('Galle'),
('Gampaha'),
('Hambantota'),
('Jaffna'),
('Kalutara'),
('Kandy'),
('Kegalle'),
('Kilinochchi'),
('Kurunegala'),
('Mannar'),
('Matale'),
('Matara'),
('Moneragala'),
('Mullaitivu'),
('Nuwara Eliya'),
('Polonnaruwa'),
('Puttalam'),
('Ratnapura'),
('Trincomalee'),
('Vavuniya');
